server:
    host: localhost
    port: 8081
database:
    type: mysql
    username: root
    password: "123456"
    host: localhost
    port: 3306
    database: hobbyhub
    charset: utf8mb4
authentication:
    jwtsecret: "1234567890"
