server:
    host: 0.0.0.0
    port: 8081
database:
    type: sqlite
    username: root
    password: "123456"
    host: localhost
    port: 3306
    database: ./database.db
    charset: utf8mb4
authentication:
    jwtsecret: "1234567890"
file:
    upload_path: ./uploads
    max_size: 10 # in MB
    allowed_types: ["png", "jpg", "jpeg", "gif", "pdf", "doc", "docx"]
