basePath: /api
definitions:
  api.FriendRequest:
    properties:
      user_id:
        description: 好友用户ID
        type: integer
    required:
    - user_id
    type: object
  api.UsernameAndPassword:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  api.newChatRequest:
    properties:
      content:
        description: 聊天内容
        type: string
      user_id_to:
        description: 接收者用户Id
        type: integer
    required:
    - content
    - user_id_to
    type: object
  models.Chat:
    properties:
      content:
        type: string
      create_time:
        type: string
      id:
        type: integer
      status_from:
        type: integer
      status_to:
        type: integer
      user_id_from:
        type: integer
      user_id_to:
        type: integer
    type: object
  models.ErrorResponse:
    properties:
      errorMessage:
        type: string
    type: object
  models.Friend:
    properties:
      apply:
        description: '0: Pending, 1: Accepted, 2: Rejected'
        type: integer
      create_time:
        type: string
      friend_id:
        type: integer
      id:
        type: integer
      user_id:
        type: integer
    type: object
  models.SuccessResponse:
    properties:
      successMessage:
        type: string
    type: object
  models.User:
    properties:
      addr:
        type: string
      createTime:
        type: string
      gender:
        type: string
      headImg:
        type: string
      id:
        type: integer
      lat:
        type: number
      lon:
        type: number
      name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: HobbyHub 后端 API 文档
  title: HobbyHub API
  version: "1.0"
paths:
  /v1/chat:
    get:
      consumes:
      - application/json
      description: 根据两个用户的id获取聊天记录列表
      parameters:
      - description: 对方用户ID
        in: query
        name: to_user_id
        required: true
        type: integer
      - description: 开始时间，格式为YYYY-MM-DD HH:MM:SS
        in: query
        name: starttime
        type: string
      - description: 结束时间，格式为YYYY-MM-DD HH:MM:SS
        in: query
        name: endtime
        type: string
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Chat'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 获取聊天记录
      tags:
      - 聊天相关接口
    post:
      consumes:
      - application/json
      description: 发送聊天消息
      parameters:
      - description: 聊天记录内容
        in: body
        name: chat
        required: true
        schema:
          $ref: '#/definitions/api.newChatRequest'
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Chat'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 发送聊天消息
      tags:
      - 聊天相关接口
  /v1/friend:
    get:
      description: 通过用户ID获取好友列表
      parameters:
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.User'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 获取好友列表
      tags:
      - 好友相关接口
    post:
      description: 通过用户ID发送好友申请
      parameters:
      - description: 好友申请信息
        in: body
        name: friendRequest
        required: true
        schema:
          $ref: '#/definitions/api.FriendRequest'
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 发送好友申请
      tags:
      - 好友相关接口
    put:
      description: 通过ID更新好友状态
      parameters:
      - description: 好友申请信息
        in: body
        name: friendRequest
        required: true
        schema:
          $ref: '#/definitions/api.FriendRequest'
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Friend'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 更新好友状态
      tags:
      - 好友相关接口
  /v1/friend/:id:
    delete:
      description: 通过ID删除好友状态
      parameters:
      - description: 需要删除的Friend ID
        in: path
        name: id
        required: true
        type: integer
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 删除好友
      tags:
      - 好友相关接口
  /v1/login:
    post:
      consumes:
      - application/json
      description: 用户名密码登录
      parameters:
      - description: 登录请求体，包含用户名和密码
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/api.UsernameAndPassword'
      produces:
      - application/json
      responses:
        "200":
          description: JWT Token
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 用户登录
      tags:
      - 用户相关接口
  /v1/user:
    get:
      description: 通过用户ID获取用户信息，可选用户id或用户名查询，优先使用用户id
      parameters:
      - description: 用户ID
        in: query
        name: id
        type: integer
      - description: 用户名
        in: query
        name: username
        type: string
      - description: JWT Token
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 获取用户信息
      tags:
      - 用户相关接口
    post:
      consumes:
      - application/json
      description: 更新用户信息
      parameters:
      - description: 用户数据，必须包含id
        in: body
        name: userInfo
        required: true
        schema:
          $ref: '#/definitions/models.User'
      - description: JWT Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 修改后的用户信息
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 更新用户信息
      tags:
      - 用户相关接口
    put:
      consumes:
      - application/json
      description: 用户名密码注册
      parameters:
      - description: 注册请求体，包含用户名和密码
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/api.UsernameAndPassword'
      produces:
      - application/json
      responses:
        "200":
          description: JWT Token
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: 用户注册
      tags:
      - 用户相关接口
swagger: "2.0"
